apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
  generation: 1
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: 2.4.0
    helm.sh/chart: flux2-2.14.1
  name: flux2-flux-check-mama
  namespace: flux-system
spec:
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: flux2-flux-check-mama  # This must match the pod template labels
  suspend: false
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: flux-system
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/version: 2.4.0
        helm.sh/chart: flux2-2.14.1
        job-name: flux2-flux-check-mama  # This label must match the selector above
      name: flux2
    spec:
      automountServiceAccountToken: true
      containers:
      - command:
        - /usr/local/bin/flux
        - check
        - --pre
        - --namespace
        - flux-system
        image: ghcr.io/fluxcd/flux-cli:v2.4.0
        imagePullPolicy: IfNotPresent
        name: flux-cli
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: flux2-flux-check
      serviceAccountName: flux2-flux-check
      terminationGracePeriodSeconds: 30
