apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
  creationTimestamp: "2025-01-11T02:41:42Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: 2.4.0
    helm.sh/chart: flux2-2.14.1
  name: flux2-flux-check
  namespace: flux-system
  resourceVersion: "8819"
  uid: 762fc0f4-e624-4819-a69f-2cb303ac3d29
spec:
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 762fc0f4-e624-4819-a69f-2cb303ac3d29
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: flux-system
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/version: 2.4.0
        controller-uid: 762fc0f4-e624-4819-a69f-2cb303ac3d29
        helm.sh/chart: flux2-2.14.1
        job-name: flux2-flux-check
      name: flux2
    spec:
      automountServiceAccountToken: true
      containers:
      - command:
        - /usr/local/bin/flux
        - check
        - --pre
        - --namespace
        - flux-system
        image: ghcr.io/fluxcd/flux-cli:v2.4.0
        imagePullPolicy: IfNotPresent
        name: flux-cli
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: flux2-flux-check
      serviceAccountName: flux2-flux-check
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastProbeTime: "2025-01-11T02:43:54Z"
    lastTransitionTime: "2025-01-11T02:43:54Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 2
  ready: 0
  startTime: "2025-01-11T02:41:42Z"
  uncountedTerminatedPods: {}
